### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by agaida** [comment]
I know that we should change the issue trackers too - but i would suggest to do this at the begin of the new release cycle.

**Comment by agaida** [comment]
@tsujan @palinek @luis-pereira @PCMan  ^^

**Comment by tsujan** [comment]
I think it's good enough; just the line about `menu-cache` can be removed because, although we still use it, it's not ours, we can't do anything about it and, sooner or later, we'll replace it with our code(s).

`libfm-qt` issue tracker can be ignored because users can't be sure whether a bug is in pcmanfm-qt or in libfm-qt -- sometimes I'm not sure either at first.

**Comment by agaida** [comment]
i'm ok with user fileing bugs in /lxqt/lxqt/issues - we can and should move it to the matching project ourself after triaging.

**Comment by palinek** [comment]
GTM

**Pull request merged**
