### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by stefonarch**
Just saw that on https://lxqt.github.io/  "Contribute" points here.

### CODE REVIEW

**Comment by stefonarch** [comment]
As I mention, it looks ready to me, it's missing only a domain name, https and GH integration with the lxqt repositories (and testing this obliviously).

**Comment by yan12125** [comment]
The new weblate instance looks quite good. I think it is time to make it official. Could you update the Weblate URL in this PR?

**Comment by stefonarch** [comment]
Done hopefully.

**Comment by yan12125** [comment]
Thanks!

**Pull request merged**
