### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ito32bit**
Remove ComptonConf
Ref: https://github.com/lxqt/compton-conf#warning

### CODE REVIEW

**Comment by stefonarch** [comment]
I noticed there is some more to update: at the bottom references to web site lxqt.org  and forum offline (→discussions),  would you like to fix those too?

**Comment by ito32bit** [comment]
Done.

**Comment by stefonarch** [comment]
Thanks!
@tsujan will this be ok with squash&merge or should the commits be squashed by the author?

**Comment by tsujan** [comment]
I merged it by using "Squash and merge." As you can see in https://github.com/lxqt/lxqt/commit/2d4b2015d6db5e452d48e711831636da3560ad5f, it's added to the history as a single commit.

**Pull request merged**
