### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by krotera**
Make LTS issues notice more prominent and clarify wording

### CODE REVIEW

**Comment by wxl** [comment]
Coming from the Ubuntu camp, I approve. In fact, I might even argue that it's worth adding "If you're not sure how this applies to you, use your distribution's bug tracker."

**Comment by krotera** [comment]
> Coming from the Ubuntu camp, I approve. In fact, I might even argue that it's worth adding "If you're not sure how this applies to you, use your distribution's bug tracker."

I was *dangerously close* to filing an issue I have on Lubuntu, even after reading that notice twice. I kept thinking it was talking about *old LTS distros*, as opposed to old LXQt versions on LTS distros. ¦ p

**Comment by wxl** [comment]
Well, thank you very much for reading carefully and for taking the time to improve it, too. BTW you probably know this but we're available downstream in lots of forms at https://lubuntu.me/links.

**Comment by stefonarch** [comment]
Any objections merging this? Found it by case....

**Comment by tsujan** [comment]
Merge it.

**Pull request merged**
