### PR TITLE
Add funding link to the GitHub page of this repo

### PR DESCRIPTION
**Pull request by yan12125**
See: https://github.com/lxqt/lxqt/issues/1846

Ref: https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

### CODE REVIEW

**Comment by wxl** [comment]
LGTM

**Comment by stefonarch** [comment]
I think first we need to improve a little the OpenCollective page: logo, text, information about how donations are intended to use and more admins.

**Comment by stefonarch** [comment]
I was thinking a link could also stay in https://github.com/lxqt/lxqt/blob/master/CONTRIBUTING.md

**Comment by yan12125** [comment]
> I was thinking a link could also stay in https://github.com/lxqt/lxqt/blob/master/CONTRIBUTING.md

Good point! I added one more short paragraph about it.

> I think first we need to improve a little the OpenCollective page: logo, text, information about how donations are intended to use and more admins.

Is there anything still missing? I don't remember details.

**Comment by stefonarch** [comment]
> Is there anything still missing? I don't remember details.

Not really IMO, but there's no plan what to do with some surplus still.

**Comment by yan12125** [comment]
> there's no plan what to do with some surplus still.

I consider that a separate issue. Current income is just enough for server expenses, and I don't think we will get more money by adding links. Instead, these changes are for making official statements. The OpenCollective page has been running for some time, but it's not explicitly mentioned in project descriptions or on the website yet.

**Comment by stefonarch** [comment]
I agree, so let us merge that now.

**Comment by yan12125** [comment]
A link to our OpenCollective page now appears on https://github.com/lxqt/lxqt

圖片

**Pull request merged**
