### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by luis-pereira**
To someone that lands on https://github.com/lxqt/lxqt it seems that LXQt
isn't being developed.

Closes https://github.com/lxqt/lxqt/issues/1888.

### CODE REVIEW

**Comment by tsujan** [comment]
As far as I'm concerned, you could merge it if you've tested it. I'm the last person you might want to review it; have never used the scripts.

> To someone that lands on https://github.com/lxqt/lxqt it seems that LXQt isn't being developed.

I agree.

**Comment by luis-pereira** [comment]
> As far as I'm concerned, you could merge it if you've tested it. I'm the last person you might want to review it; have never used the scripts.

It has nothing to do with the scripts. It simply updates the subproject's commit. We should update it ta least when tagging a release.

**Review by tsujan — APPROVED** [review]
> It has nothing to do with the scripts.

Then, GTM, of course.

Actually, I wanted to ask you about it immediately before the release but I guess you were busy.

**Comment by luis-pereira** [comment]
> Actually, I wanted to ask you about it immediately before the release but I guess you were busy.

Yes, I was away. When tagging we also should update the subproject's commit.

**Comment by tsujan** [comment]
> When tagging we also should update the subproject's commit.

I understand. I use this repository only for the announcement — because of ts name. Next time I'll request an update.

**Pull request merged**
