### PR TITLE
Qt6: Added libdbusmenu-lxqt

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
This would not support building Qt5 branches of `libqtxdg` and `lxqt-qtplugin`, I think we should add this to the scripts. Thoughts? @pereira @tsujan

**Comment by tsujan** [comment]
I think we can wait until the Qt6 port is complete in git.

**Comment by stefonarch** [comment]
The build script will fail now as those 2 are missing. I'll test it later.

**Comment by tsujan** [comment]
Yes, it should fail now. I think it'll also fail if we add them because some components depend on the older lxqt-build-tools. If so, it's inevitable: we're in a transition period.

**Comment by tsujan** [comment]
Oh, it seems that the older lxqt-build-tools is still included. So, theoretically, the problem should be fixed once this PR is merged? A test?

**Comment by stefonarch** [comment]
In fact I'm setting up an arch WM on my debian PC, for this and else.

**Comment by stefonarch** [comment]
Inserting `lxqt2-build-tools` wasn't the thing to do: lxqt-build-tools builds now `lxqt2-build-tools` as it has been merged. 

The script stops early as the  `lxqt-build-tools` from LXQt 1.4 is missing, a checkout and compiling to the prerelease commit is needed, same for `libqtxdg` and `lxqt-qtplugin` and `libfm-qt` I think.

**Comment by tsujan** [comment]
OK. So, am I right thinking that it's inevitable, as long as we're in the transition stage?

**Comment by tsujan** [comment]
Or it means that if you remove `lxqt2-build-tools`, it'll work?

**Comment by stefonarch** [comment]
Still to test.

**Comment by stefonarch** [comment]
For some reason the PR doesn't insert the empty folder for   'libdbusmenu-lxqt`, so `git submodule init` doesn't include it yet. See https://github.com/lxqt/lxqt/commit/1d3702be6eee639d2ea28f39d3478e0a5b1ed04a

**Comment by yan12125** [comment]
I'm not familiar with how other repos are organized in this repo. In general, I use `git submodule add <remote_git_url> <local_path>`, which will create the folder for committing.

**Comment by Chiitoo** [comment]
As far as I remember correct-like, 'git' in general does not track empty directories (only took a quick look around to see if I remember right-like at all).

**Comment by yan12125** [comment]
> As far as I remember correct-like, 'git' in general does not track empty directories (only took a quick look around to see if I remember right-like at all).

Usually git doesn't. Submodules are special :)

**Comment by stefonarch** [comment]
> I'm not familiar with how other repos are organized in this repo. In general, I use `git submodule add <remote_git_url> <local_path>`, which will create the folder for committing.

I'll try to redo this PR with that, thanks.

**Comment by Chiitoo** [comment]
> Usually git doesn't. Submodules are special :)

Yeah... realised a bit too late it was about submodules, oops!

Sorry about that.

**Comment by stefonarch** [comment]
Looks working now, thanks. As reminder:
`lxqt$ git submodule add ../libdbusmenu-lxqt ./libdbusmenu-lxqt`
New PR is here https://github.com/lxqt/lxqt/pull/2539

**Pull request closed without merging**
